# Generated by Django 4.2.27 on 2026-01-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_usernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(blank=True, choices=[('novel', 'Novel'), ('short_stories', 'Short Stories'), ('poetry', 'Poetry')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('fantasy', 'Fantasy'), ('sci_fi', 'Science Fiction'), ('biography', 'Biography'), ('self_help', 'Self Help')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'author'], name='books_book_title_b7b426_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['genre', 'book_type'], name='books_book_genre_53d2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['published_year'], name='books_book_publish_9a145c_idx'),
        ),
    ]
